/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.DiliverSystem.view.Rider;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lk.ijse.DiliverSystem.controller.ManageOrderDitalController;
import lk.ijse.DiliverSystem.controller.MangeSubmitOrderController;
import lk.ijse.DiliverSystem.dto.OrderDitailsDTO;

/**
 *
 * @author Viraj jayasanka
 */
public class GetOrderDitails extends javax.swing.JFrame {

    /**
     * Creates new form GetOrderDitails
     */
    public GetOrderDitails(java.awt.Frame parent, boolean modal) {
        initComponents();
        loadAllCustomers();
       
        setSize(1129, 206);
         setLocationRelativeTo(null);
    }
   private void loadAllCustomers(){
        String id  = getOrder.txtGetOrderID.getText();
        
        System.out.println(id);
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);

        try {
            List<OrderDitailsDTO> SenterDTOs = ManageOrderDitalController.getOrderDeatilsID(id);

            if (SenterDTOs == null) {
                return;
            }

            for (OrderDitailsDTO customerDTO1 : SenterDTOs) {
                Object[] rowData = {
                    customerDTO1.getOrderDetailID(),
                    customerDTO1.getOrderID(),
                    customerDTO1.getTeleponeOperterName(),
                    customerDTO1.getCustomerID(),
                    customerDTO1.getDeleiveryChes(),
                    customerDTO1.getTotal(),
                    customerDTO1.getTime(),
                    customerDTO1.getDate()
                   
                };
                dtm.addRow(rowData);
                
               // ArrayList<TakeOrderDTO> list =takeOrderDTO.?uComboBox2.getSelectedItem());
            }

        } catch (Exception ex) {
            Logger.getLogger(GetOrderDitails.class.getName()).log(Level.SEVERE, null, ex);
        }

 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 1080, 120));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setText("Get Order Details Panel");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
