/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.DiliverSystem.view.Rider;

import com.sun.prism.paint.Color;
import java.rmi.server.UnicastRemoteObject;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.DiliverSystem.controller.ManageLoginRiderController;
import lk.ijse.DiliverSystem.controller.ManageRiderController;
import lk.ijse.DiliverSystem.controller.ManageRiderGetOrderController;
import lk.ijse.DiliverSystem.controller.MangeSubmitOrderController;
import lk.ijse.DiliverSystem.dto.DiliveryRiderDTO;
import lk.ijse.DiliverSystem.dto.LoginRiderDTO;
import lk.ijse.DiliverSystem.dto.RiderGetOrderDTO;
import lk.ijse.DiliverSystem.dto.SubmitOrderDTO;
import lk.ijse.DiliverSystem.observer.Observer;

/**
 *
 * @author Viraj jayasanka
 */
public class getOrder extends javax.swing.JFrame implements lk.ijse.DiliverSystem.observer.Observer{

    /**
     * Creates new form getOrder
     */
    public getOrder(java.awt.Frame parent, boolean modal) {
        initComponents();
        loadAllCustomers();
        setSize(831, 325);
        setLocationRelativeTo(null);
        loadData();
        valisdasion();
         
         
           try {
            UnicastRemoteObject.exportObject(this, 0);
           //  Mange.getSubject().registerObserver(this);
              MangeSubmitOrderController.getSubject().registerObserver(this);
        } catch (Exception ex) {
          Logger.getLogger(getOrder.class.getName()).log(Level.SEVERE, null, ex);
          
             }
    }
 public void valisdasion(){
        jButton3.setEnabled(false);
        jButton2.setEnabled(false);
        jComboBox2.setEnabled(false);
        jButton1.setEnabled(false);
    }
 public void valisdasion2(){
        jButton3.setEnabled(true);
        jButton2.setEnabled(true);
        jComboBox2.setEnabled(true);
        jButton1.setEnabled(true);
    }
     private void loadAllCustomers(){
        
        SubmitOrder submitOrder= new SubmitOrder();
        
        DefaultTableModel dtm = (DefaultTableModel) tableGetOrderTable.getModel();
        dtm.setRowCount(0);

        try {
            List<SubmitOrderDTO> SenterDTOs = MangeSubmitOrderController.getAllSubmitOrders();

            if (SenterDTOs == null) {
                return;
            }

            for (SubmitOrderDTO customerDTO1 : SenterDTOs) {
                Object[] rowData = {
                    customerDTO1.getSubmitOrderID(),
                    customerDTO1.getOrderID(),
                    customerDTO1.getTeleponeOperterName(),
                    customerDTO1.getCustomerId(),
                    customerDTO1.getTotal(),
                    customerDTO1.getPayment(),
                    customerDTO1.getTime(),
                    customerDTO1.getDate()
                   
                };
                dtm.addRow(rowData);
                
               // ArrayList<TakeOrderDTO> list =takeOrderDTO.?uComboBox2.getSelectedItem());
            }

        } catch (Exception ex) {
            Logger.getLogger(getOrder.class.getName()).log(Level.SEVERE, null, ex);
        }

 }
     
     
//      private void loadAllRider(){
//
//        DefaultTableModel dtm = (DefaultTableModel) jTable3.getModel();
//        dtm.setRowCount(0);
//
//        try {
//            List<DiliveryRiderDTO> riderDTOs = ManageRiderController.getAllDiliverRiders();
//
//            if (riderDTOs == null) {
//                return;
//            }
//
//            for (DiliveryRiderDTO diliveryRiderDTO : riderDTOs) {
//                Object[] rowData = {
//                    diliveryRiderDTO.getId(),
//                    diliveryRiderDTO.getRiderNAme()
//                    
//                };
//                dtm.addRow(rowData);
//            }
//
//        } catch (Exception ex) {
//            Logger.getLogger(RiderManage.class.getName()).log(Level.SEVERE, null, ex);
//        }
//            }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGetOrderTable = new javax.swing.JTable();
        txtSubmitOderID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtGetOrderID = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtTeponeOperterName = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        CustomerId = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setText("Select Rider Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));

        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 236, 160, 30));

        tableGetOrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SubmitOrder ID", "Order ID", "T.O.N", "Customer ID", "Total", "Dicriptions"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableGetOrderTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tableGetOrderTableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tableGetOrderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableGetOrderTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableGetOrderTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 800, 100));

        txtSubmitOderID.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        txtSubmitOderID.setText("S.O.ID");
        jPanel1.add(txtSubmitOderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        jLabel3.setText("Submit Order ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        txtGetOrderID.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        txtGetOrderID.setText("Order ID");
        jPanel1.add(txtGetOrderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        jLabel5.setText("Order ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jLabel6.setText("T.O.N");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        jButton1.setText("Get Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 140, 40));

        txtTeponeOperterName.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        txtTeponeOperterName.setText("T.O.N");
        jPanel1.add(txtTeponeOperterName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 60, -1));

        txtCustomerID.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        txtCustomerID.setForeground(new java.awt.Color(255, 0, 0));
        txtCustomerID.setText("51");
        jPanel1.add(txtCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 50, -1));

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel13.setText("Get Order");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jButton2.setText("Show Order Ditals");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 140, 40));

        jButton3.setText("Show customer Ditalis");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 160, 40));

        CustomerId.setText("Customer ID");
        jPanel1.add(CustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, -1));

        jLabel9.setText("Total");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, -1, -1));

        txtTotal.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        txtTotal.setText("total");
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 80, -1));

        jSeparator1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 800, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 320));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       rDitailsPane customerDitails = new rDitailsPane(getOrder.this, true);
       customerDitails.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tableGetOrderTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableGetOrderTableMouseClicked
        String customerId  = tableGetOrderTable.getValueAt(tableGetOrderTable.getSelectedRow(), 0).toString();
        String name  = tableGetOrderTable.getValueAt(tableGetOrderTable.getSelectedRow(), 1).toString();
        String address  = tableGetOrderTable.getValueAt(tableGetOrderTable.getSelectedRow(), 2).toString();
        String TelponeNO  = tableGetOrderTable.getValueAt(tableGetOrderTable.getSelectedRow(), 3).toString();
        String otherNo  = tableGetOrderTable.getValueAt(tableGetOrderTable.getSelectedRow(), 4).toString();
        //String TxtAriya  = tableGetOrderTable.getValueAt(tableGetOrderTable.getSelectedRow(), 7).toString();
   
        getOrder. txtSubmitOderID.setText(customerId);
        getOrder.txtGetOrderID.setText(name);       
        getOrder.txtTeponeOperterName.setText(address);      
        getOrder.txtCustomerID.setText(TelponeNO);     
        getOrder.txtTotal.setText(otherNo); 
        valisdasion2();
      
    }//GEN-LAST:event_tableGetOrderTableMouseClicked

    private void tableGetOrderTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tableGetOrderTableAncestorAdded
      
    }//GEN-LAST:event_tableGetOrderTableAncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        RiderGetOrderDTO getOrderDTO = new RiderGetOrderDTO(
         
                Integer.parseInt( txtSubmitOderID.getText()),
                Integer.parseInt( txtGetOrderID.getText()),
                txtTeponeOperterName.getText(),
                txtCustomerID.getText(),
                Double.parseDouble(txtTotal.getText()),
                jComboBox2.getSelectedItem().toString(),
                MainPanelRider.TimeLabel.getText()
        );
        try {
            boolean resalat = ManageRiderGetOrderController.addRiderGetOrder(getOrderDTO);
            boolean Delete = MangeSubmitOrderController.deleteSubmitOrder(Integer.parseInt(txtSubmitOderID.getText()));
            
            if(resalat == true){
                JOptionPane.showMessageDialog(this,"Order is Getting Sussesis");
            }else{
               JOptionPane.showMessageDialog(this,"Order is Getting UNSussesis"); 
            }
        } catch (Exception ex) {
            Logger.getLogger(getOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
       GetOrderDitails getOrderDitails = new GetOrderDitails(getOrder.this, true);
       getOrderDitails.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel CustomerId;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tableGetOrderTable;
    public static javax.swing.JLabel txtCustomerID;
    public static javax.swing.JLabel txtGetOrderID;
    public static javax.swing.JLabel txtSubmitOderID;
    public static javax.swing.JLabel txtTeponeOperterName;
    public static javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
private void loadData(){
        try{
            ArrayList<LoginRiderDTO> allItem =(ArrayList<LoginRiderDTO>) ManageLoginRiderController.getAllLoginRiders();
            if(allItem == null){
             return ;
            }
            for(LoginRiderDTO item :allItem){
                Object[]rowData ={item.getRiderNAme()};
                jComboBox2.addItem(item.getRiderNAme());
            }
        } catch (Exception ex) {
            Logger.getLogger(getOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
}
//
//    @Override
//    public void updateObservers() throws Exception {
//        loadAllCustomers();
//    }

    @Override
    public void updateObservers() throws Exception {
        loadAllCustomers();
    }

}
