/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.DiliverSystem.view.Rider;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.rmi.Remote;
import java.rmi.server.UnicastRemoteObject;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import lk.ijse.DiliverSystem.controller.ManageLoginRiderController;
import lk.ijse.DiliverSystem.controller.ManageRiderController;
import lk.ijse.DiliverSystem.controller.ManageRiderGetOrderController;
import lk.ijse.DiliverSystem.controller.MangeSubmitOrderController;
import lk.ijse.DiliverSystem.dto.LoginRiderDTO;
import lk.ijse.DiliverSystem.dto.RiderGetOrderDTO;
import lk.ijse.DiliverSystem.dto.SubmitOrderDTO;


/**
 *
 * @author Viraj jayasanka
 */
public class MainPanelRider extends javax.swing.JFrame implements lk.ijse.DiliverSystem.observer.Observer{

    /**
     * Creates new form MainPanel
     */
    public MainPanelRider() {
        initComponents();
        jPanel2.setBackground(new Color(228,239,186,110));
        jPanel3.setBackground(new Color(228,239,186,110));
        setSize(1369, 770);
        loadAllCustomers();
        loadAllLoginRider();
        loadAllOrderss();
        validashion();
        setTime();
        
        
           try {
            UnicastRemoteObject.exportObject(this, 0);
            ManageLoginRiderController.getSubject().registerObserver(this); 
            MangeSubmitOrderController.getSubject().registerObserver(this);
            ManageRiderGetOrderController.getSubject().registerObserver(this);    
        } catch (Exception ex) {
          Logger.getLogger(MainPanelRider.class.getName()).log(Level.SEVERE, null, ex);
          
             }

        
    }
    
     void setTime(){
        new Timer(0, new ActionListener() {

           
            public void actionPerformed(ActionEvent e) {
                Date dt = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("hh : mm : ss a");
                TimeLabel.setText(sdf.format(dt));
            }

        } ).start();
    }
     
     
  private void validashion(){
      jButton1.setEnabled(false);
      jButton7.setEnabled(false);
  }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        TimeLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCalendarCombo1 = new org.freixas.jcalendar.JCalendarCombo();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        GetOrdertabel = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        SubmitOrderTabel1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Time", "Rider Name"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 190, 550));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/DiliverSystem/Image/FontAwesome_f019(0)_32.png"))); // NOI18N
        jButton3.setText("Loging Rider");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 40));

        jButton2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton2.setText("Show RIPORDTS");
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 170, 40));

        jButton4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/DiliverSystem/Image/Log out (2).png"))); // NOI18N
        jButton4.setText("Log Out");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 190, 40));

        jButton5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton5.setText("All Orders");
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 210, 40));

        jButton6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton6.setText("Massange");
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 10, 210, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 1310, 60));

        TimeLabel.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        TimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        TimeLabel.setText("Time");
        jPanel1.add(TimeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 100, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Time");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        jProgressBar1.setBackground(new java.awt.Color(255, 0, 0));
        jProgressBar1.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        jProgressBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jProgressBar1.setEnabled(false);
        jProgressBar1.setIndeterminate(true);
        jProgressBar1.setInheritsPopupMenu(true);
        jProgressBar1.setOpaque(true);
        jProgressBar1.setString("VJ Delivery System");
        jProgressBar1.setStringPainted(true);
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, 370, 20));

        jLabel3.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("WELCOME TO RIDER");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));
        jPanel1.add(jCalendarCombo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, 30));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GetOrdertabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Submitorder ID", "OrderID", "T.O.N", "Customer ID", "Total", "RiderName", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        GetOrdertabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GetOrdertabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(GetOrdertabel);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 1080, 140));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/DiliverSystem/Image/FontAwesome_f067(0)_32.png"))); // NOI18N
        jButton1.setText("get Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 210, 170, 40));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/DiliverSystem/Image/Entypo_d83d(3)_45_1.png"))); // NOI18N
        jButton7.setText("Submit Order");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 450, 160, 40));

        SubmitOrderTabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Submitorder ID", "Order ID", "T.O.N", "Customer ID", "Total", "Dicrption", "Time", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SubmitOrderTabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitOrderTabel1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(SubmitOrderTabel1);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 1080, 140));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 1120, 540));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/DiliverSystem/Image/OrdermanuImage.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 770));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1770, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       LogingRiderFram logingRider = new LogingRiderFram(MainPanelRider.this, true);
       logingRider.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        getOrder order = new getOrder(MainPanelRider.this, true);
       order.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        SaveOrder order = new SaveOrder(MainPanelRider.this, true);
       order.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void SubmitOrderTabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitOrderTabel1MouseClicked
       jButton1.setEnabled(true);
    }//GEN-LAST:event_SubmitOrderTabel1MouseClicked

    private void GetOrdertabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GetOrdertabelMouseClicked
       jButton7.setEnabled(true);
    }//GEN-LAST:event_GetOrdertabelMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       LogoutRider order = new LogoutRider(MainPanelRider.this, true);
       order.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
                     UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPanelRider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPanelRider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPanelRider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPanelRider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPanelRider().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GetOrdertabel;
    private javax.swing.JTable SubmitOrderTabel1;
    public static javax.swing.JLabel TimeLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    public static org.freixas.jcalendar.JCalendarCombo jCalendarCombo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
//
//    @Override
//    public void updateObservers() throws Exception {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
//
////    @Override
//    public void updateObservers() throws Exception {
//        loadAllOrderss();
//        loadAllCustomers();
//    }
   
    private void loadAllCustomers(){

        DefaultTableModel dtm = (DefaultTableModel) SubmitOrderTabel1.getModel();
        dtm.setRowCount(0);

        try {
            List<SubmitOrderDTO> SenterDTOs = MangeSubmitOrderController.getAllSubmitOrders();

            if (SenterDTOs == null) {
                return;
            }

            for (SubmitOrderDTO customerDTO1 : SenterDTOs) {
                Object[] rowData = {
                    customerDTO1.getSubmitOrderID(),
                    customerDTO1.getOrderID(),
                    customerDTO1.getTeleponeOperterName(),
                    customerDTO1.getCustomerId(),
                    customerDTO1.getTotal(),
                    customerDTO1.getPayment(),
                    customerDTO1.getTime(),
                    customerDTO1.getDate()
                   
                };
                dtm.addRow(rowData);
            }

        } catch (Exception ex) {
            Logger.getLogger(MainPanelRider.class.getName()).log(Level.SEVERE, null, ex);
        }

 }
   
    
   // Login Tabel
    private void loadAllLoginRider(){

        DefaultTableModel dtm = (DefaultTableModel) jTable3.getModel();
        dtm.setRowCount(0);

        try {
            List<LoginRiderDTO> SenterDTOs = ManageLoginRiderController.getAllLoginRiders();

            if (SenterDTOs == null) {
                return;
            }

            for (LoginRiderDTO loginRiderDTO : SenterDTOs) {
                Object[] rowData = {
                  
                    loginRiderDTO.getTime(),
                    loginRiderDTO.getRiderNAme()
                };
                dtm.addRow(rowData);
            }

        } catch (Exception ex) {
            Logger.getLogger(MainPanelRider.class.getName()).log(Level.SEVERE, null, ex);
        }

 }
    


 private void loadAllOrderss(){

        DefaultTableModel dtm = (DefaultTableModel) GetOrdertabel.getModel();
        dtm.setRowCount(0);

             try {

                 
            List<RiderGetOrderDTO> SenterDTOs = ManageRiderGetOrderController.getAllRiderGetOrder();
            if (SenterDTOs == null) {
                return;
            }

            for (RiderGetOrderDTO getOrderDTO : SenterDTOs) {
                Object[] rowData = {
                    getOrderDTO.getSubmitOrderID(),
                    getOrderDTO.getOrderid(),
                    getOrderDTO.getTeleponeOperterName(),
                    getOrderDTO.getCustomerID(),
                    getOrderDTO.getTotal(),
                    getOrderDTO.getRiderName(),
                    getOrderDTO.getTime()
                    
                };
                dtm.addRow(rowData);
            }

        } catch (Exception ex) {
            Logger.getLogger(MainPanelRider.class.getName()).log(Level.SEVERE, null, ex);
     }
 }

    @Override
    public void updateObservers() throws Exception {
        loadAllLoginRider();
        loadAllOrderss();
        loadAllCustomers();
        
    }
}
