/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.DiliverSystem.view.Rider;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lk.ijse.DiliverSystem.controller.ManageCustomerDetailControoler;
import lk.ijse.DiliverSystem.controller.ManageRiderController;
import lk.ijse.DiliverSystem.controller.MangeSubmitOrderController;
import lk.ijse.DiliverSystem.dto.AddCustomerDetailsDTO;
import static lk.ijse.DiliverSystem.view.Rider.getOrder.txtCustomerID;

/**
 *
 * @author Viraj jayasanka
 */
public class rDitailsPane extends javax.swing.JFrame {
private DefaultTableModel defaultTableModel;
    /**
     * Creates new form getCustomerDitails
     */
    public rDitailsPane(java.awt.Frame parent, boolean modal) {
        initComponents();
      setSize(878, 223);
        setLocationRelativeTo(null);
        defaultTableModel = (DefaultTableModel) CutamerDitails.getModel();
        
        loadAllCustomers();
        
    }
    
//    private void loadData(){
//       defaultTableModel.setRowCount(0);
//        try{
//             
//            ArrayList<AddCustomerDetailsDTO> allItem =(ArrayList<AddCustomerDetailsDTO>) ManageCustomerDetailControoler.SeachCustomerID(id);
//            if(allItem == null){
//             return ;
//            }
//            for(AddCustomerDetailsDTO item :allItem){
//                Object[]rowData ={item.getCustomeID()};
//                 defaultTableModel.addRow(rowData);
//            }
//        } catch (Exception ex) {
//            Logger.getLogger(getCustomerDitails.class.getName()).log(Level.SEVERE, null, ex);
//        }
//}
  private void loadAllCustomers(){
        String id  = getOrder.txtCustomerID.getText();
        //SubmitOrder submitOrder= new SubmitOrder();
        
        DefaultTableModel dtm = (DefaultTableModel) CutamerDitails.getModel();
        dtm.setRowCount(0);

        try {
            List<AddCustomerDetailsDTO> SenterDTOs = ManageCustomerDetailControoler.SeachCustomerID(id);

            if (SenterDTOs == null) {
                return;
            }

            for (AddCustomerDetailsDTO customerDTO1 : SenterDTOs) {
                Object[] rowData = {
                    customerDTO1.getSaveOrderID(),
                    customerDTO1.getCustomeID(),
                    customerDTO1.getCustomertelponeNO(),
                    customerDTO1.getTime(),
                    customerDTO1.getDate(),
                    customerDTO1.getCustomerName()
                   // customerDTO1.getTime(),
                   // customerDTO1.getDate()
                   
                };
                dtm.addRow(rowData);
                
                
               // ArrayList<TakeOrderDTO> list =takeOrderDTO.?uComboBox2.getSelectedItem());
            }

        } catch (Exception ex) {
            Logger.getLogger(rDitailsPane.class.getName()).log(Level.SEVERE, null, ex);
        }

 }
////private void loadData(){
////       
////    try{
////            
//      //  int id = Integer.parseInt(CustomerID.getText());
//     int id = 67;
//          System.out.print(id);
//          AddCustomerDetailsDTO allItem= (AddCustomerDetailsDTO) ManageCustomerDetailControoler.SeachCustomerID(id);
//            if(allItem == null){
//             return ;
//            }
//            
//                Object[]rowData ={allItem.getCustomeID(),allItem.getCustomerName(),allItem.getCustomerAddress(),allItem.getCustomertelponeNO(),allItem.getCustomerOtherNO(),allItem.getDate()};
//                //jComboBox2.addItem(item.getRiderNAme());
//            
//        } catch (Exception ex) {
//            Logger.getLogger(getCustomerDitails.class.getName()).log(Level.SEVERE, null, ex);
//        }
//}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CutamerDitails = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CutamerDitails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(CutamerDitails);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 850, 150));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setText("Customer Ditails");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 200, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CutamerDitails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
