/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.DiliverySystem.View.Manager;

import java.rmi.server.UnicastRemoteObject;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import lk.ijse.DiliverSystem.dto.LasetOrderSaveDTO;
import lk.ijse.DiliverSystem.observer.Observer;
import lk.ijse.DilverSystem.controller.ManageLastOrderSaveController;
import lk.ijse.DilverSystem.controller.MangeCallSenterController;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.engine.util.JRLoader;

/**
 *
 * @author Viraj jayasanka
 */
public class AllOrders extends javax.swing.JPanel implements Observer{
  private DefaultTableModel dtmCustomer;
    /**
     * Creates new form SaveOrdersDitels
     */
    public AllOrders() {
        initComponents();
        Enabalethod();
        loadAllSaveOrder();
        jLabel5.setText(Double.toString(getSum()));
        getMax();
       jLabel11.setText(Float.toString(getAverage()));
           try {
            UnicastRemoteObject.exportObject(this, 0);
               ManageLastOrderSaveController.getSubject().registerObserver(this);
        } catch (Exception ex) {
          Logger.getLogger(AllOrders.class.getName()).log(Level.SEVERE, null, ex);
          
             }
     
    }
  
    
   private double getSum(){
       
        double rowcount = lastOrderTAbel.getRowCount();
        double sum= 0;
        for(double i = 0 ; i < rowcount; i++){
            sum = sum+Double.parseDouble(lastOrderTAbel.getValueAt((int) i, 9).toString());
        }
        return sum;
    }
   
    public float getAverage(){
        float sum  = (float) getSum();
        double rowsCount = lastOrderTAbel.getRowCount();
        float average = (float) (sum/rowsCount);
        return average;
    }
    
   public void getMax(){
     
       ArrayList<Double> list = new ArrayList<>();
       for(double i=0; i < lastOrderTAbel.getRowCount(); i++){
           list.add(Double.parseDouble(lastOrderTAbel.getValueAt((int) i, 9).toString()));
       }
       double max = Collections.max(list);
       double min = Collections.min(list);
       
       jLabel6.setText(Double.toString(max));
       jLabel7.setText(Double.toString(min));
   }
    

     private void loadAllSaveOrder(){
      
        
        DefaultTableModel dtm = (DefaultTableModel) lastOrderTAbel.getModel();
        dtm.setRowCount(0);

        try {
            List<LasetOrderSaveDTO> SenterDTOs = ManageLastOrderSaveController.getAllLastOrderSaves();

            if (SenterDTOs == null) {
                return;
            }

            for (LasetOrderSaveDTO lasetOrderSaveDTO : SenterDTOs) {
                Object[] rowData = {
                    lasetOrderSaveDTO.getSaveOrderId(),
                    lasetOrderSaveDTO.getSumbitOrderID(),
                    lasetOrderSaveDTO.getOrderID(),
                    lasetOrderSaveDTO.getCustomerID(),
                    lasetOrderSaveDTO.getTeleponrOPerterName(),
                    lasetOrderSaveDTO.getRiderName(),
                    lasetOrderSaveDTO.getGetOrderTime(),
                    lasetOrderSaveDTO.getOutOrderTime(),
                    lasetOrderSaveDTO.getPayament(),
                    lasetOrderSaveDTO.getTotal(),
                    lasetOrderSaveDTO.getDate()
                   
                };
                dtm.addRow(rowData);
                
               // ArrayList<TakeOrderDTO> list =takeOrderDTO.?uComboBox2.getSelectedItem());
            }

        } catch (Exception ex) {
            Logger.getLogger(AllOrders.class.getName()).log(Level.SEVERE, null, ex);
        }

 }
       private void Enabalethod(){
        DeletBtn.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lastOrderTAbel = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DeletBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lastOrderTAbel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SaveOrderId", "SumbitOrderID", "OrderID", "CustomerID", "TeleponrOPerterName", "RiderName", "GetOrderTime", "OutOrderTime", "Payament", "Total", "date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lastOrderTAbel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lastOrderTAbelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        lastOrderTAbel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lastOrderTAbelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lastOrderTAbel);
        if (lastOrderTAbel.getColumnModel().getColumnCount() > 0) {
            lastOrderTAbel.getColumnModel().getColumn(5).setPreferredWidth(12);
            lastOrderTAbel.getColumnModel().getColumn(10).setMinWidth(20);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1130, 530));

        jButton2.setText("Show report");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 620, 160, 40));

        jButton3.setText("Save Report");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(975, 618, 140, 40));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setText("All Order");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 30));

        DeletBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/DiliverSystem/image/delete customer ican1.png"))); // NOI18N
        DeletBtn.setToolTipText("Delete Order");
        DeletBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletBtnActionPerformed(evt);
            }
        });
        add(DeletBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 620, 110, 40));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setText("Order ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 640, -1, -1));

        jLabel3.setText("Order ID");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, -1, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel4.setText("Total ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, 20));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Total");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 100, 20));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Max");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 70, 20));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Min");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 60, 20));

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel8.setText("Average");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel9.setText("Min");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, -1, 20));

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel10.setText("Max");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, 20));

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("Average");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      try {
            JasperReport comJasperReport = (JasperReport)JRLoader.loadObject(AllOrders.class.getResource("/lk/ijse/DiliverySystem/Jasperrepors/Blank_A4_1.jasper"));
            JasperPrint filledReport = JasperFillManager.fillReport(comJasperReport, new HashMap<>(),new JRTableModelDataSource(lastOrderTAbel.getModel()));
            JFileChooser fileChooser = new JFileChooser();

            fileChooser.setAcceptAllFileFilterUsed(false);
            fileChooser.setFileFilter(new FileNameExtensionFilter("HTML Files('.html)", "html"));
            fileChooser.showSaveDialog(this);

            String filePath = fileChooser.getSelectedFile().getAbsolutePath();
            filePath+=".html";
            JasperExportManager.exportReportToHtmlFile(filledReport,filePath);

        } catch (JRException ex) {
            Logger.getLogger(AllOrders.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         try {
            JasperReport comJasperReport = (JasperReport)JRLoader.loadObject(AllOrders.class.getResource("/lk/ijse/DiliverySystem/Jasperrepors/Blank_A4_1.jasper"));
                                                                                                                                                                                
            JasperPrint filledReport = JasperFillManager.fillReport(comJasperReport, new HashMap<>(),new JRTableModelDataSource(lastOrderTAbel.getModel()));
            mypanel MyjViewer = new mypanel(filledReport);
            MyjViewer.setVisible(true);

        } catch (JRException ex) {
            Logger.getLogger(AllOrders.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lastOrderTAbelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastOrderTAbelMouseClicked
       String customerId  = lastOrderTAbel.getValueAt(lastOrderTAbel.getSelectedRow(), 0).toString();
       
   
        AllOrders. jLabel2.setText(customerId);
         DeletBtn.setEnabled(true);
       
    }//GEN-LAST:event_lastOrderTAbelMouseClicked

    private void DeletBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletBtnActionPerformed
       int id  = Integer.parseInt(jLabel2.getText());
       
      try {
          boolean Resalt = ManageLastOrderSaveController.deleteLastOrderSave(id);
          if(Resalt){
               JOptionPane.showMessageDialog(this, "Order is Delete");
          }else{
              JOptionPane.showMessageDialog(this, "Order is Delete ");
      }
          Enabalethod();
           jLabel5.setText(Double.toString(getSum()));
        getMax();
       jLabel11.setText(Float.toString(getAverage()));
      } catch (Exception ex) {
          Logger.getLogger(AllOrders.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_DeletBtnActionPerformed

    private void lastOrderTAbelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lastOrderTAbelAncestorAdded
      
    }//GEN-LAST:event_lastOrderTAbelAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeletBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    public static javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable lastOrderTAbel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateObservers() throws Exception {
         loadAllSaveOrder();
    }


}
