/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.DiliverSystem.view.Casher;

import java.rmi.server.UnicastRemoteObject;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.DiliverSystem.controller.ManageCustomerDetailControoler;
import lk.ijse.DiliverSystem.controller.MangeCallSenterController;
import lk.ijse.DiliverSystem.dto.AddCustomerDetailsDTO;
import lk.ijse.DiliverSystem.observer.Observer;

/**
 *
 * @author Viraj jayasanka
 */
public class SearchCustomer extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form SearchCustomer
     */
    public SearchCustomer() {
        initComponents();
         
         setSize(402, 509);
         setLocationRelativeTo(null);
        
     // loadAllCustomerDetails();
     // SeachCustomer();
      loadAllCustomerDetails();
         
         
           try {
            UnicastRemoteObject.exportObject(this, 0);
               ManageCustomerDetailControoler.getSubject().registerObserver(this);
        } catch (Exception ex) {
          Logger.getLogger(AddCustomerPanel.class.getName()).log(Level.SEVERE, null, ex);
          
             }
         
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SearchCustomerTabel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchCustomerTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Save Order ID", "Customer ID", "Order ID", "Customer Name"
            }
        ));
        jScrollPane1.setViewportView(SearchCustomerTabel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 80, 380, 400));

        jLabel1.setText("Customer Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 180, 30));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
//      String name= jTextField1.getText();
//      
//       try{
//           AddCustomerDetailsDTO acddto = (AddCustomerDetailsDTO) ManageCustomerDetailControoler.SearchCustomerDetail(name);
//           if(acddto == null){
//               JOptionPane.showMessageDialog(this, "item Not found");
//           }else{
//               System.out.println(acddto);
//               Object [] rowData ={acddto.getCustomeID(),acddto.getCustomerAddress(),acddto.getCustomerOtherNO(),acddto.getSaveOrderID()};
//               DefaultTableModel dtm = (DefaultTableModel) SearchCustomerTabel.getModel();
//               dtm.setRowCount(0);
//               dtm.addRow(rowData);
//                SearchCustomerTabel.requestFocusInWindow();
//                System.out.print(dtm);
//           }
//       } catch (Exception ex) {
//            Logger.getLogger(SearchCustomer.class.getName()).log(Level.SEVERE, null, ex);
//        }
//                   
//       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
     
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable SearchCustomerTabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

 private void loadAllCustomerDetails(){

     
//      String name= jTextField1.getText();
//      
//       try{
//           AddCustomerDetailsDTO acddto = (AddCustomerDetailsDTO) ManageCustomerDetailControoler.SearchCustomerDetail(name);
//           if(acddto == null){
//               JOptionPane.showMessageDialog(this, "item Not found");
//           }else{
//               System.out.println(acddto);
//               Object [] rowData ={acddto.getCustomeID(),acddto.getCustomerAddress(),acddto.getCustomerOtherNO(),acddto.getSaveOrderID()};
//               DefaultTableModel dtm = (DefaultTableModel) SearchCustomerTabel.getModel();
//               dtm.setRowCount(0);
//               dtm.addRow(rowData);
//           }
//       } catch (Exception ex) {
//            Logger.getLogger(SearchCustomer.class.getName()).log(Level.SEVERE, null, ex);
//        }

        DefaultTableModel dtm = (DefaultTableModel) SearchCustomerTabel.getModel();
        dtm.setRowCount(0);

             try {
                           
            List<AddCustomerDetailsDTO> SenterDTOs = ManageCustomerDetailControoler.getAllCustomerDetails();
            //List<AddCustomerDetailsDTO> SenterDTOs = ManageCustomerDetailControoler.SearchCustomerDetail(jTextField1.getText());
            if (SenterDTOs == null) {
                return;
            }

            for (AddCustomerDetailsDTO callSenterDTO : SenterDTOs) {
                Object[] rowData = {
                    callSenterDTO.getSaveOrderID(),
                    callSenterDTO.getOrderID(),
                    callSenterDTO.getCustomeID(),
                    callSenterDTO.getCustomerName(),
                    callSenterDTO.getCustomerAddress(),
                    callSenterDTO.getCustomertelponeNO(),
                    callSenterDTO.getCustomerOtherNO(),          
                    callSenterDTO.getDate(),
                    callSenterDTO.getTime()
                };
                dtm.addRow(rowData);
               //System.out.print(dtm);
            }

        } catch (Exception ex) {
            Logger.getLogger(SearchCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
 }

//  private void SeachCustomer(){     
//   
//     
//      
//      DefaultTableModel dtm = (DefaultTableModel) SearchCustomerTabel.getModel();
//        dtm.setRowCount(0);
//
//             try {
//
//                 
//            List<AddCustomerDetailsDTO> SenterDTOs = ManageCustomerDetailControoler.SearchCustomerDetail(jTextField1.getText());
//            if (SenterDTOs == null) {
//                return;
//            }
//
//            for (AddCustomerDetailsDTO callSenterDTO : SenterDTOs) {
//                Object[] rowData = {
//                    callSenterDTO.getSaveOrderID(),
//                    callSenterDTO.getOrderID(),
//                    callSenterDTO.getCustomeID(),
//                    callSenterDTO.getCustomerName(),
//                    callSenterDTO.getCustomerAddress(),
//                    callSenterDTO.getCustomertelponeNO(),
//                    callSenterDTO.getCustomerOtherNO(),          
//                    callSenterDTO.getDate(),
//                    callSenterDTO.getTime()
//                };
//                dtm.addRow(rowData);
//            }
//
//        } catch (Exception ex) {
//            Logger.getLogger(orderDetalTabel.class.getName()).log(Level.SEVERE, null, ex);
//        } 
//   }        
//
//    @Override
//    public void updateObservers() throws Exception {
//        SearchCustomerTabel.selectAll();
//        SeachCustomer();
//    }

    @Override
    public void updateObservers() throws Exception {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
