/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.DiliverSystem.view.Casher;

import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.DataOutput;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileReader;
import java.net.ServerSocket;
import java.net.Socket;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Viraj jayasanka
 */
public class SendItemSet extends javax.swing.JFrame {
 static ServerSocket ss;
 static Socket s;
 static DataInputStream dis;
 static DataOutput dout;
 
 
    /**
     * Creates new form SendItemSet
     */
    public SendItemSet() {
        initComponents();
        setSize(440, 479);
        setLocationRelativeTo(null);
       // massageServer();
    }
//    
//    public void massageServer(){
//     
//        String msgin ="";
//        try {
//            ss = new ServerSocket(5050);
//            s =ss.accept();
//            
//            dis = new DataInputStream(dis);
//            dout = new DataOutputStream(s.getOutputStream());
//            
//            while(msgin.equals("Exit")){
//                msgin = dis.readUTF();
//                msAriya.setText(msAriya.getText().trim()+"\n"+msgin);
//            }
//            
//            
//            
//            
//            
//        } catch (Exception e) {
//        }
//     
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        msAriya = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        msAriya.setColumns(20);
        msAriya.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        msAriya.setRows(5);
        jScrollPane1.setViewportView(msAriya);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 410, 320));

        jButton1.setText("Send Ceff Order Item List");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 400, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String filePath="C:\\Users\\Viraj jayasanka\\Documents\\NetBeansProjects\\VJ-DILIVER-SYSTEM\\src\\lk\\ijse\\DiliverSystem\\view\\Casher\\FileWeite.sql";
        File file = new File(filePath);
        try{
            FileReader fw = new FileReader (file);
            BufferedReader bw = new BufferedReader(fw);
             msAriya.read(bw,null);
             
                    
           
           // for(int i=0 ; i<Files.lines(path); i++){
//                //for(int j = 0 ; j<OrelTabel.getColumnCount(); j++){
//                    String read =list.toString().split+"       ");
//               }
//                bw.newLine();
           // }
            bw.close();
            msAriya.requestFocus();
            fw.close();
        }catch(Exception ex){
             Logger.getLogger(SendItemSet.class.getName()).log(Level.SEVERE, null, ex);
        }
      PlaceOrderFrom();
        try {
            
            String  magout = "";
            magout = msAriya.getText().trim();
            dout.writeUTF(magout);
            
            
        } catch (Exception e) {
        }
     
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea msAriya;
    // End of variables declaration//GEN-END:variables
   private void PlaceOrderFrom(){
    msAriya.setEnabled(true);
    //jTextArea1.getText();
    int refa =1325 + (int) (Math.random())*4238;
     //int columns = OrelTabel.getSelectedRow();
     // int rows = OrelTabel.getSelectedRow();
    //===================================================================
//    DefaultTableModel dtm = (DefaultTableModel) OrelTabel.getModel();
//    Object[] rowData = {ItemName, orderQty, unitPrice, z};
//    dtm.addRow(rowData);
    Calendar timer = Calendar.getInstance();
    timer.getTime();
      //  SimpleTextFormat  format = new SimpleTextFormat(OrelTabelAncestorAdded("ItemName:orderQty"));
    SimpleDateFormat tTime = new SimpleDateFormat("MM:mm:ss");
    tTime.format(timer.getTime());
    SimpleDateFormat Tdate = new SimpleDateFormat("DD:MMM:YYY");
    Tdate.format(timer.getTime());
   //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
   
                  
                msAriya.append(""
                        + "\t\n" +
                       // "\n+++++++++++++++++++++++++=\t " + 
//                         "Reference\t\t\t\t"+ orderQty +
                     // "\n========================\t " +    
//                       "\n===VJ==DELIVERY==SYSTEM==\t " +
//                        "\n=========================\t " +
////                        "\n"+ OrelTabel.getColumnName(0)+
////                        "  ||       "+ OrelTabel.getColumnName(1)+
////                        "  ||       "+ OrelTabel.getColumnName(2)+
////                        "  ||       "+ OrelTabel.getColumnName(3)+
////                        "\n|| "+ OrelTabel.getValueAt(columns, 0).toString() +
////                        "  ||       "+ OrelTabel.getValueAt(columns, 1).toString() +
////                        "  ||       "+ OrelTabel.getValueAt(columns, 2).toString() +
////                        "  ||       "+ OrelTabel.getValueAt(columns, 3).toString() +
//                           // "\nTable"+ OrelTabel. +
//                    "\nTable"+ TakeOrderDTO.getValueAt(row, 0).toString() +
                        "\nDate: " + Tdate.format(timer.getTime()) + 
                        "\t\tTime:  " +  tTime.format(timer.getTime()) +
                        "\n\n\t  Next Order Coming Soon............. \n" +
                        "\n\n\t\n" +
                        //  "\n=Update Save Data You User OrderDitel Button==\t " + 
                        //  "\n=Data Is Save Sassuess Full==\t " +      
                       "" );
                          
  
   }

}
